CREATE DATABASE IF NOT EXISTS userservice;
CREATE DATABASE IF NOT EXISTS orderservice;
CREATE DATABASE IF NOT EXISTS productservice;
CREATE DATABASE IF NOT EXISTS appointmentservice;
CREATE DATABASE IF NOT EXISTS notificationservice;
CREATE DATABASE IF NOT EXISTS paymentservice;
CREATE DATABASE IF NOT EXISTS recordservice;
